export class Timers {
    public static readonly MANDARINE_EXPIRED_SESSIONS: string = "MANDARINE_EXPIRED_SESSIONS";
    public static readonly MANDARINE_TIMER_REGISTRY: string = "MANDARINE_TIMER_REGISTRY_{0}";
    public static readonly MANDARINE_MICROSERVICE_HEALTH_INTERVAL: string = "MANDARINE_MICROSERVICE_HEALTH_INTERVAL_{0}";
    public static readonly MANDARINE_AUTOMATIC_HEALTHCHECK_INTERVAL: string = "MANDARINE_AUTOMATIC_HEALTHCHECK_INTERVAL";
}