name: Mandarine Microservices

on: [push, pull_request]

jobs:
  build:
    name: Mandarine Microservices (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        deno: ["v1.9.0"]
        redis: [6.2]
      fail-fast: true
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v2
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: Set NATS Server Version
        run: echo "NATS_VERSION=v2.2.1" >> $GITHUB_ENV          
      - name: Get nats-server
        run: |
          wget "https://github.com/nats-io/nats-server/releases/download/$NATS_VERSION/nats-server-$NATS_VERSION-linux-amd64.zip" -O tmp.zip
          unzip tmp.zip
          mv nats-server-$NATS_VERSION-linux-amd64 nats-server
          rm nats-server/README.md LICENSE
      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: "true"             
      - name: run tests
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: GITHUB=true deno test -c tsconfig.json --reload --allow-all --unstable --fail-fast tests/integration-tests/microservices.ts       